[package]
name = "capter-cli"
version = "0.1.0"
authors = ["Filip Stefansson <filip.stefansson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
regex = "1"
indicatif = "0.15.0"
console = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
glob = "0.3.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
handlebars = "3.5.1"
chrono = { version = "0.4", features = ["serde"] }
ci_info = "0.13.2"
