name: test-build

# runs on push but ignores tags (release)
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-- --test-threads 1'

      - name: run
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: test --token ${{ secrets.CAPTER_TOKEN }}

      - name: upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    name: deploy
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/alpha'
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-semver
          version: 1.0.0-alpha.3
          use-tool-cache: true

      - run: cargo semver bump pre alpha

      - run: echo "VERSION=$(cargo semver get)" >> $GITHUB_ENV

      - run: echo $VERSION

      - name: commit new version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: alpha
          commit_message: v${{ env.VERSION }}
          tagging_message: v${{ env.VERSION }}
          commit_user_name: github-actions
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          body: v${{ env.VERSION }}
          draft: false
          prerelease: true
